### ISSUE TITLE
use native date picker

### ISSUE THREAD

**Issue by jimmywarting** [Givo29/timesince#2]
could you replace the custom date picker with `<input type="datetime-local">` it will also support picking hour/min and do it in a localized way.

**Comment by jimmywarting** [comment]
not every country starts the day of the week with sunday

**Comment by Givo29** [comment]
Hey @jimmywarting, just converted timesince to use a datetime-local field. Give it a test and let me know if what I did is what you had in mind.

Thanks for the idea :)

**Comment by jimmywarting** [comment]
Much better. Also a lot more mobile friendly!

Just one more thing. Could you maybe make the end date default to now instead? It's called time since after all and i do not think ppl will go into the feature as much

**Comment by jimmywarting** [comment]
Btw i saw that you where using luxon. I do not think that is necessary.
You have a method to get/set dates with input.valueAsDate it's a lot simpler to use

**Comment by Givo29** [comment]
@jimmywarting Thanks for finding that local date issue, I didn't notice. Turns out that JavaScript's `toISOString()` ignores the client's timezone...

As for luxon, I'm using it mainly to handle the time calculations, especially for when the "Concatenate Units" setting is on, so it's very useful in that regard.
